name: Integration Test
run-name: Running Integration tests for API endpoints
on: [push]
jobs:
  Run-Integration-Tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache virtual environment
        uses: actions/cache@v4
        id: cache-virtual-environment
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Create virtual environment if not exist
        run: python -m venv .venv && source .venv/bin/activate && 
             pip install -r requirements.txt
        if: steps.cache-virtual-environment.outputs.cache-hit != 'true'

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -v tests/
